/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Entries
         * @description 列出条目（优先从 SQLite 索引读取）
         */
        get: operations["list_entries_entries_get"];
        put?: never;
        /**
         * Create Entry
         * @description 创建条目
         */
        post: operations["create_entry_entries_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entries/{entry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Entry
         * @description 获取单个条目
         */
        get: operations["get_entry_entries__entry_id__get"];
        /**
         * Update Entry
         * @description 更新条目
         */
        put: operations["update_entry_entries__entry_id__put"];
        post?: never;
        /**
         * Delete Entry
         * @description 删除条目
         */
        delete: operations["delete_entry_entries__entry_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entries/search/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Entries
         * @description 全文搜索条目（使用 SQLite FTS5）
         */
        get: operations["search_entries_entries_search_query_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entries/{entry_id}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Project Progress
         * @description 获取项目进度（子任务完成率）
         */
        get: operations["get_project_progress_entries__entry_id__progress_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entries/admin/sync-vectors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync Vectors
         * @description 同步所有条目到向量数据库（Qdrant）
         */
        post: operations["sync_vectors_entries_admin_sync_vectors_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search Entries
         * @description 语义搜索条目
         */
        post: operations["search_entries_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/knowledge-graph/{concept}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Knowledge Graph
         * @description 获取概念的知识图谱
         */
        get: operations["get_knowledge_graph_knowledge_graph__concept__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/related-concepts/{concept}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Related Concepts
         * @description 获取相关概念
         */
        get: operations["get_related_concepts_related_concepts__concept__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/learning-path/{concept}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Learning Path
         * @description 获取概念的学习路径
         *
         *     返回：
         *     - prerequisites: 前置知识（需要先学习的概念）
         *     - current_level: 当前掌握程度（基于相关笔记/任务数量推断）
         *     - next_steps: 下一步建议学习的内容
         *     - related_projects: 相关项目
         *     - related_notes: 相关笔记
         */
        get: operations["get_learning_path_learning_path__concept__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/review/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Daily Report
         * @description 获取日报
         */
        get: operations["get_daily_report_review_daily_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/review/weekly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Weekly Report
         * @description 获取周报
         */
        get: operations["get_weekly_report_review_weekly_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/review/monthly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Monthly Report
         * @description 获取月报
         */
        get: operations["get_monthly_report_review_monthly_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Detect Intent
         * @description 检测用户输入的意图
         *
         *     使用 LLM 进行智能意图识别，支持：
         *     - create: 创建任务/笔记
         *     - read: 搜索/查询
         *     - update: 更新条目
         *     - delete: 删除条目
         *     - knowledge: 知识图谱
         *     - review: 回顾总结
         *     - help: 帮助说明
         */
        post: operations["detect_intent_intent_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Parse
         * @description 解析自然语言文本，流式返回结果（SSE）
         *
         *     使用 LangGraph Checkpointer 管理对话历史，
         *     通过 thread_id（session_id）实现多轮对话。
         */
        post: operations["parse_parse_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/session/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Clear Session
         * @description 清空指定会话的对话历史
         *
         *     Args:
         *         session_id: 会话 ID（对应 LangGraph thread_id）
         */
        delete: operations["clear_session_session__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat
         * @description 统一聊天接口（合并意图检测和处理）
         *
         *     一次请求完成：
         *     1. 意图检测（可跳过）
         *     2. 根据意图分发处理
         *
         *     返回 SSE 流式响应：
         *     - event: intent  - 意图检测结果
         *     - event: content - 流式内容（create 意图）
         *     - event: done    - 完成，包含 need_client_action 表示是否需要前端额外处理
         */
        post: operations["chat_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description 健康检查
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ChatRequest
         * @description 统一聊天请求
         */
        ChatRequest: {
            /**
             * Text
             * @description 用户输入文本
             */
            text: string;
            /**
             * Session Id
             * @description 会话 ID
             * @default default
             */
            session_id: string;
            /**
             * Skip Intent
             * @description 跳过意图检测（前端已确认为 create）
             * @default false
             */
            skip_intent: boolean;
        };
        /**
         * ConceptNode
         * @description 概念节点
         */
        ConceptNode: {
            /** Name */
            name: string;
            /** Category */
            category?: string | null;
            /** Description */
            description?: string | null;
        };
        /**
         * ConceptRelationModel
         * @description 概念关系
         */
        ConceptRelationModel: {
            /** Name */
            name: string;
            /** Relationship */
            relationship: string;
            /** Category */
            category?: string | null;
        };
        /**
         * DailyReport
         * @description 日报响应
         */
        DailyReport: {
            /** Date */
            date: string;
            task_stats: components["schemas"]["TaskStats"];
            note_stats: components["schemas"]["NoteStats"];
            /** Completed Tasks */
            completed_tasks?: {
                [key: string]: unknown;
            }[];
            /** Ai Summary */
            ai_summary?: string | null;
        };
        /**
         * EntryCreate
         * @description 创建条目请求
         */
        EntryCreate: {
            /**
             * Category
             * @description 条目分类: project/task/note/inbox
             */
            category: string;
            /**
             * Title
             * @description 标题
             */
            title: string;
            /**
             * Content
             * @description 内容
             * @default
             */
            content: string;
            /**
             * Tags
             * @description 标签
             */
            tags?: string[];
            /**
             * Parent Id
             * @description 父条目ID
             */
            parent_id?: string | null;
            /**
             * Status
             * @description 状态: waitStart/doing/complete/paused/cancelled
             */
            status?: string | null;
            /**
             * Priority
             * @description 优先级: high/medium/low
             */
            priority?: string | null;
            /**
             * Planned Date
             * @description 计划日期
             */
            planned_date?: string | null;
            /**
             * Time Spent
             * @description 耗时（分钟）
             */
            time_spent?: number | null;
        };
        /**
         * EntryListResponse
         * @description 条目列表响应
         */
        EntryListResponse: {
            /** Entries */
            entries: components["schemas"]["EntryResponse"][];
            /**
             * Total
             * @default 0
             */
            total: number;
        };
        /**
         * EntryResponse
         * @description 条目响应
         */
        EntryResponse: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Content */
            content: string;
            /** Category */
            category: string;
            /** Status */
            status: string;
            /**
             * Priority
             * @default medium
             */
            priority: string;
            /** Tags */
            tags: string[];
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
            /** Planned Date */
            planned_date?: string | null;
            /** Completed At */
            completed_at?: string | null;
            /** Time Spent */
            time_spent?: number | null;
            /** Parent Id */
            parent_id?: string | null;
            /** File Path */
            file_path: string;
        };
        /**
         * EntryUpdate
         * @description 更新条目请求
         */
        EntryUpdate: {
            /**
             * Title
             * @description 新标题
             */
            title?: string | null;
            /**
             * Content
             * @description 新内容
             */
            content?: string | null;
            /**
             * Status
             * @description 新状态: waitStart/doing/complete/paused/cancelled
             */
            status?: string | null;
            /**
             * Priority
             * @description 新优先级: high/medium/low
             */
            priority?: string | null;
            /**
             * Tags
             * @description 新标签
             */
            tags?: string[] | null;
            /**
             * Parent Id
             * @description 父条目ID
             */
            parent_id?: string | null;
            /**
             * Planned Date
             * @description 计划日期
             */
            planned_date?: string | null;
            /**
             * Time Spent
             * @description 耗时（分钟）
             */
            time_spent?: number | null;
            /**
             * Completed At
             * @description 完成时间
             */
            completed_at?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description 健康检查响应
         */
        HealthResponse: {
            /** Status */
            status: string;
        };
        /**
         * IntentRequest
         * @description 意图识别请求
         */
        IntentRequest: {
            /**
             * Text
             * @description 用户输入文本
             */
            text: string;
            /**
             * Context
             * @description 上下文信息
             */
            context?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * IntentResponse
         * @description 意图识别响应
         */
        IntentResponse: {
            /**
             * Intent
             * @description 识别的意图类型
             */
            intent: string;
            /**
             * Confidence
             * @description 置信度
             * @default 1
             */
            confidence: number;
            /**
             * Entities
             * @description 提取的实体
             */
            entities?: {
                [key: string]: unknown;
            };
            /**
             * Query
             * @description 搜索/操作关键词
             */
            query?: string | null;
            /**
             * Response Hint
             * @description 响应提示
             */
            response_hint?: string | null;
        };
        /**
         * KnowledgeGraphResponse
         * @description 知识图谱响应
         */
        KnowledgeGraphResponse: {
            center?: components["schemas"]["ConceptNode"] | null;
            /**
             * Connections
             * @default []
             */
            connections: components["schemas"]["ConceptRelationModel"][];
        };
        /**
         * LearningPathResponse
         * @description 学习路径响应
         */
        LearningPathResponse: {
            /** Concept */
            concept: string;
            /**
             * Prerequisites
             * @default []
             */
            prerequisites: components["schemas"]["ConceptNode"][];
            /**
             * Current Level
             * @default unknown
             */
            current_level: string;
            /**
             * Next Steps
             * @default []
             */
            next_steps: components["schemas"]["ConceptNode"][];
            /**
             * Related Projects
             * @default []
             */
            related_projects: string[];
            /**
             * Related Notes
             * @default []
             */
            related_notes: string[];
        };
        /**
         * MonthlyReport
         * @description 月报响应
         */
        MonthlyReport: {
            /** Month */
            month: string;
            task_stats: components["schemas"]["TaskStats"];
            note_stats: components["schemas"]["NoteStats"];
            /** Weekly Breakdown */
            weekly_breakdown?: {
                [key: string]: unknown;
            }[];
            /** Ai Summary */
            ai_summary?: string | null;
        };
        /**
         * NoteStats
         * @description 笔记统计
         */
        NoteStats: {
            /**
             * Total
             * @description 笔记总数
             */
            total: number;
            /**
             * Recent Titles
             * @description 最近笔记标题
             */
            recent_titles?: string[];
        };
        /**
         * ParseRequest
         * @description 解析请求
         */
        ParseRequest: {
            /**
             * Text
             * @description 自然语言文本
             */
            text: string;
            /**
             * Session Id
             * @description 会话 ID（对应 LangGraph thread_id）
             * @default default
             */
            session_id: string;
        };
        /**
         * ProjectProgressResponse
         * @description 项目进度响应
         */
        ProjectProgressResponse: {
            /** Project Id */
            project_id: string;
            /** Total Tasks */
            total_tasks: number;
            /** Completed Tasks */
            completed_tasks: number;
            /** Progress Percentage */
            progress_percentage: number;
            /** Status Distribution */
            status_distribution: {
                [key: string]: unknown;
            };
        };
        /**
         * RelatedConceptsResponse
         * @description 相关概念响应
         */
        RelatedConceptsResponse: {
            /** Concept */
            concept: string;
            /** Related */
            related: components["schemas"]["ConceptNode"][];
        };
        /**
         * SearchRequest
         * @description 搜索请求
         */
        SearchRequest: {
            /**
             * Query
             * @description 搜索查询
             */
            query: string;
            /**
             * Limit
             * @description 返回数量
             * @default 5
             */
            limit: number;
        };
        /**
         * SearchResponse
         * @description 搜索响应
         */
        SearchResponse: {
            /** Results */
            results: components["schemas"]["app__routers__search__SearchResult"][];
        };
        /**
         * SessionResponse
         * @description 会话操作响应
         */
        SessionResponse: {
            /** Status */
            status: string;
            /**
             * Message
             * @default
             */
            message: string;
        };
        /**
         * SuccessResponse
         * @description 成功响应
         */
        SuccessResponse: {
            /** Success */
            success: boolean;
            /**
             * Message
             * @default
             */
            message: string;
        };
        /**
         * TaskStats
         * @description 任务统计
         */
        TaskStats: {
            /**
             * Total
             * @description 总任务数
             */
            total: number;
            /**
             * Completed
             * @description 已完成数
             */
            completed: number;
            /**
             * Doing
             * @description 进行中数
             */
            doing: number;
            /**
             * Wait Start
             * @description 待开始数
             */
            wait_start: number;
            /**
             * Completion Rate
             * @description 完成率
             */
            completion_rate: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WeeklyReport
         * @description 周报响应
         */
        WeeklyReport: {
            /** Start Date */
            start_date: string;
            /** End Date */
            end_date: string;
            task_stats: components["schemas"]["TaskStats"];
            note_stats: components["schemas"]["NoteStats"];
            /** Daily Breakdown */
            daily_breakdown?: {
                [key: string]: unknown;
            }[];
            /** Ai Summary */
            ai_summary?: string | null;
        };
        /**
         * SearchResult
         * @description 搜索结果
         */
        app__api__schemas__entry__SearchResult: {
            /** Entries */
            entries: components["schemas"]["EntryResponse"][];
            /** Query */
            query: string;
        };
        /**
         * SearchResult
         * @description 搜索结果项
         */
        app__routers__search__SearchResult: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Score */
            score: number;
            /** Type */
            type: string;
            /** Tags */
            tags: string[];
            /** File Path */
            file_path: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_entries_entries_get: {
        parameters: {
            query?: {
                /** @description 条目类型: project/task/note/inbox */
                type?: string | null;
                /** @description 状态: waitStart/doing/complete/paused/cancelled */
                status?: string | null;
                /** @description 标签筛选（逗号分隔） */
                tags?: string | null;
                /** @description 父条目ID（用于获取子任务） */
                parent_id?: string | null;
                /** @description 开始日期 (YYYY-MM-DD) */
                start_date?: string | null;
                /** @description 结束日期 (YYYY-MM-DD) */
                end_date?: string | null;
                /** @description 返回数量限制 */
                limit?: number;
                /** @description 偏移量 */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntryListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_entry_entries_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EntryCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_entry_entries__entry_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_entry_entries__entry_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EntryUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_entry_entries__entry_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_entries_entries_search_query_get: {
        parameters: {
            query: {
                /** @description 搜索关键词 */
                q: string;
                /** @description 返回数量限制 */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["app__api__schemas__entry__SearchResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_progress_entries__entry_id__progress_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectProgressResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_vectors_entries_admin_sync_vectors_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
        };
    };
    search_entries_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_knowledge_graph_knowledge_graph__concept__get: {
        parameters: {
            query?: {
                /** @description 关系深度 */
                depth?: number;
            };
            header?: never;
            path: {
                concept: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeGraphResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_related_concepts_related_concepts__concept__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                concept: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelatedConceptsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_learning_path_learning_path__concept__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                concept: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LearningPathResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_daily_report_review_daily_get: {
        parameters: {
            query?: {
                /** @description 日期 (YYYY-MM-DD)，默认今天 */
                date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_weekly_report_review_weekly_get: {
        parameters: {
            query?: {
                /** @description 开始日期 (YYYY-MM-DD)，默认本周一 */
                start_date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeeklyReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_monthly_report_review_monthly_get: {
        parameters: {
            query?: {
                /** @description 月份 (YYYY-MM)，默认本月 */
                month?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonthlyReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    detect_intent_intent_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IntentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    parse_parse_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_session_session__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
