/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Entries
         * @description 列出条目（优先从 SQLite 索引读取）
         */
        get: operations["list_entries_entries_get"];
        put?: never;
        /**
         * Create Entry
         * @description 创建条目
         */
        post: operations["create_entry_entries_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entries/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Entries
         * @description 导出条目数据
         */
        get: operations["export_entries_entries_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entries/{entry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Entry
         * @description 获取单个条目
         */
        get: operations["get_entry_entries__entry_id__get"];
        /**
         * Update Entry
         * @description 更新条目
         */
        put: operations["update_entry_entries__entry_id__put"];
        post?: never;
        /**
         * Delete Entry
         * @description 删除条目
         */
        delete: operations["delete_entry_entries__entry_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entries/search/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Entries
         * @description 全文搜索条目（使用 SQLite FTS5）
         */
        get: operations["search_entries_entries_search_query_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entries/{entry_id}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Project Progress
         * @description 获取项目进度（子任务完成率）
         */
        get: operations["get_project_progress_entries__entry_id__progress_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entries/admin/sync-vectors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync Vectors
         * @description 同步所有条目到向量数据库（Qdrant）
         */
        post: operations["sync_vectors_entries_admin_sync_vectors_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search Entries
         * @description 语义搜索条目
         */
        post: operations["search_entries_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/knowledge-graph/{concept}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Knowledge Graph
         * @description 获取概念的知识图谱
         */
        get: operations["get_knowledge_graph_knowledge_graph__concept__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/related-concepts/{concept}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Related Concepts
         * @description 获取相关概念
         */
        get: operations["get_related_concepts_related_concepts__concept__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/learning-path/{concept}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Learning Path
         * @description 获取概念的学习路径
         *
         *     返回：
         *     - prerequisites: 前置知识（需要先学习的概念）
         *     - current_level: 当前掌握程度（基于相关笔记/任务数量推断）
         *     - next_steps: 下一步建议学习的内容
         *     - related_projects: 相关项目
         *     - related_notes: 相关笔记
         */
        get: operations["get_learning_path_learning_path__concept__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/review/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Daily Report
         * @description 获取日报
         */
        get: operations["get_daily_report_review_daily_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/review/weekly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Weekly Report
         * @description 获取周报
         */
        get: operations["get_weekly_report_review_weekly_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/review/monthly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Monthly Report
         * @description 获取月报
         */
        get: operations["get_monthly_report_review_monthly_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/review/trend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Trend Data
         * @description 获取趋势数据
         */
        get: operations["get_trend_data_review_trend_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Detect Intent
         * @description 检测用户输入的意图
         *
         *     使用 LLM 进行智能意图识别，支持：
         *     - create: 创建任务/笔记
         *     - read: 搜索/查询
         *     - update: 更新条目
         *     - delete: 删除条目
         *     - knowledge: 知识图谱
         *     - review: 回顾总结
         *     - help: 帮助说明
         */
        post: operations["detect_intent_intent_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Parse
         * @description 解析自然语言文本，流式返回结果（SSE）
         *
         *     使用 LangGraph Checkpointer 管理对话历史，
         *     通过 thread_id（{user_id}:{session_id}）实现多轮对话隔离。
         */
        post: operations["parse_parse_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/session/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Clear Session
         * @description 清空指定会话的对话历史
         *
         *     Args:
         *         session_id: 会话 ID（对应 LangGraph thread_id）
         */
        delete: operations["clear_session_session__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat
         * @description 统一聊天接口（一站式处理意图识别和操作执行）
         *
         *     一次请求完成：
         *     1. 意图检测（可跳过）
         *     2. 根据意图执行操作（create/update/delete/read 等）
         *     3. 多选场景返回 confirm 事件，前端确认后携带 confirm 参数再次调用
         *
         *     SSE 事件：
         *     - event: intent  - 意图检测结果
         *     - event: content - 流式内容（create 意图）
         *     - event: created - 创建成功
         *     - event: updated - 更新成功
         *     - event: deleted - 删除成功
         *     - event: confirm - 需要用户确认（多选场景）
         *     - event: results - 搜索结果（read 意图）
         *     - event: done    - 完成
         *     - event: error   - 错误
         */
        post: operations["chat_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sessions
         * @description 获取当前用户的所有会话列表
         *
         *     返回会话 ID、标题、创建时间、更新时间
         */
        get: operations["list_sessions_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Session Messages
         * @description 获取指定会话的消息历史
         *
         *     从 LangGraph checkpointer 读取消息
         */
        get: operations["get_session_messages_sessions__session_id__messages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Session
         * @description 删除会话（包括元数据和对话历史）
         */
        delete: operations["delete_session_sessions__session_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Session
         * @description 更新会话元数据（如标题）
         */
        patch: operations["update_session_sessions__session_id__patch"];
        trace?: never;
    };
    "/playground/llm-test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Test Llm
         * @description 测试 LLM 配置是否正常工作
         *
         *     发送一个简单的测试消息，返回 LLM 的响应和配置信息
         *     注意：此端点仅在开发环境可用
         */
        get: operations["test_llm_playground_llm_test_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Feedbacks
         * @description 获取当前用户的反馈列表
         */
        get: operations["list_feedbacks_feedback_get"];
        put?: never;
        /**
         * Submit Feedback
         * @description 提交反馈：本地先写入，后台异步上报 log-service
         */
        post: operations["submit_feedback_feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feedback/{feedback_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Feedback
         * @description 获取单条反馈详情
         */
        get: operations["get_feedback_feedback__feedback_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description 注册新用户
         */
        post: operations["register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description 用户登录，返回 access token
         */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description 登出（前端清除 token）
         */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Me
         * @description 获取当前用户信息
         */
        get: operations["get_me_auth_me_get"];
        /**
         * Update Me
         * @description 更新当前用户信息（onboarding_completed 等）
         */
        put: operations["update_me_auth_me_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/claim-default-data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Claim Default Data
         * @description 显式将 `_default` 历史数据认领到当前用户
         */
        post: operations["claim_default_data_auth_claim_default_data_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description 健康检查
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ChatRequest
         * @description 统一聊天请求
         */
        ChatRequest: {
            /**
             * Text
             * @description 用户输入文本
             */
            text: string;
            /**
             * Session Id
             * @description 会话 ID
             * @default default
             */
            session_id: string;
            /**
             * Skip Intent
             * @description 跳过意图检测（前端已确认为 create）
             * @default false
             */
            skip_intent: boolean;
            /** @description 确认操作（多选场景） */
            confirm?: components["schemas"]["ConfirmAction"] | null;
        };
        /**
         * ConceptNode
         * @description 概念节点
         */
        ConceptNode: {
            /** Name */
            name: string;
            /** Category */
            category?: string | null;
            /** Description */
            description?: string | null;
        };
        /**
         * ConceptRelationModel
         * @description 概念关系
         */
        ConceptRelationModel: {
            /** Name */
            name: string;
            /** Relationship */
            relationship: string;
            /** Category */
            category?: string | null;
        };
        /**
         * ConfirmAction
         * @description 确认操作
         */
        ConfirmAction: {
            /**
             * Action
             * @description 操作类型: update/delete
             */
            action: string;
            /**
             * Item Id
             * @description 用户选择的条目 ID
             */
            item_id: string;
        };
        /**
         * DailyReport
         * @description 日报响应
         */
        DailyReport: {
            /** Date */
            date: string;
            task_stats: components["schemas"]["TaskStats"];
            note_stats: components["schemas"]["NoteStats"];
            /** Completed Tasks */
            completed_tasks?: {
                [key: string]: unknown;
            }[];
            /** Ai Summary */
            ai_summary?: string | null;
        };
        /**
         * DefaultDataClaimResult
         * @description `_default` 历史数据认领结果
         */
        DefaultDataClaimResult: {
            /** Claimed */
            claimed: boolean;
            /**
             * Reason
             * @default
             */
            reason: string;
            /**
             * Sqlite Entries Claimed
             * @default 0
             */
            sqlite_entries_claimed: number;
            /**
             * Markdown Files Copied
             * @default 0
             */
            markdown_files_copied: number;
            /**
             * Markdown Files Skipped
             * @default 0
             */
            markdown_files_skipped: number;
            /**
             * Session Count Claimed
             * @default 0
             */
            session_count_claimed: number;
        };
        /**
         * EntryCreate
         * @description 创建条目请求
         */
        EntryCreate: {
            /**
             * Category
             * @description 条目分类: project/task/note/inbox
             */
            category: string;
            /**
             * Title
             * @description 标题
             */
            title: string;
            /**
             * Content
             * @description 内容
             * @default
             */
            content: string;
            /**
             * Tags
             * @description 标签
             */
            tags?: string[];
            /**
             * Parent Id
             * @description 父条目ID
             */
            parent_id?: string | null;
            /**
             * Status
             * @description 状态: waitStart/doing/complete/paused/cancelled
             */
            status?: string | null;
            /**
             * Priority
             * @description 优先级: high/medium/low
             */
            priority?: string | null;
            /**
             * Planned Date
             * @description 计划日期
             */
            planned_date?: string | null;
            /**
             * Time Spent
             * @description 耗时（分钟）
             */
            time_spent?: number | null;
        };
        /**
         * EntryListResponse
         * @description 条目列表响应
         */
        EntryListResponse: {
            /** Entries */
            entries: components["schemas"]["EntryResponse"][];
            /**
             * Total
             * @default 0
             */
            total: number;
        };
        /**
         * EntryResponse
         * @description 条目响应
         */
        EntryResponse: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Content */
            content: string;
            /** Category */
            category: string;
            /** Status */
            status: string;
            /**
             * Priority
             * @default medium
             */
            priority: string;
            /** Tags */
            tags: string[];
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
            /** Planned Date */
            planned_date?: string | null;
            /** Completed At */
            completed_at?: string | null;
            /** Time Spent */
            time_spent?: number | null;
            /** Parent Id */
            parent_id?: string | null;
            /** File Path */
            file_path: string;
        };
        /**
         * EntryUpdate
         * @description 更新条目请求
         */
        EntryUpdate: {
            /**
             * Title
             * @description 新标题
             */
            title?: string | null;
            /**
             * Content
             * @description 新内容
             */
            content?: string | null;
            /**
             * Category
             * @description 条目分类: project/task/note/inbox
             */
            category?: string | null;
            /**
             * Status
             * @description 新状态: waitStart/doing/complete/paused/cancelled
             */
            status?: string | null;
            /**
             * Priority
             * @description 新优先级: high/medium/low
             */
            priority?: string | null;
            /**
             * Tags
             * @description 新标签
             */
            tags?: string[] | null;
            /**
             * Parent Id
             * @description 父条目ID
             */
            parent_id?: string | null;
            /**
             * Planned Date
             * @description 计划日期
             */
            planned_date?: string | null;
            /**
             * Time Spent
             * @description 耗时（分钟）
             */
            time_spent?: number | null;
            /**
             * Completed At
             * @description 完成时间
             */
            completed_at?: string | null;
        };
        /**
         * FeedbackItem
         * @description 单条反馈记录
         */
        FeedbackItem: {
            /** Id */
            id: number;
            /** User Id */
            user_id: string;
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /**
             * Severity
             * @default medium
             */
            severity: string;
            /** Log Service Issue Id */
            log_service_issue_id?: number | null;
            /**
             * Status
             * @default pending
             */
            status: string;
            /** Created At */
            created_at: string;
        };
        /**
         * FeedbackListResponse
         * @description 反馈列表响应
         */
        FeedbackListResponse: {
            /** Items */
            items: components["schemas"]["FeedbackItem"][];
            /** Total */
            total: number;
        };
        /**
         * FeedbackRequest
         * @description 前端反馈请求
         */
        FeedbackRequest: {
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /**
             * Severity
             * @default medium
             * @enum {string}
             */
            severity: "low" | "medium" | "high" | "critical";
        };
        /**
         * FeedbackResponse
         * @description 反馈提交响应
         */
        FeedbackResponse: {
            /** Success */
            success: boolean;
            /** Feedback */
            feedback: {
                [key: string]: unknown;
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description 健康检查响应
         */
        HealthResponse: {
            /** Status */
            status: string;
        };
        /**
         * IntentRequest
         * @description 意图识别请求
         */
        IntentRequest: {
            /**
             * Text
             * @description 用户输入文本
             */
            text: string;
            /**
             * Context
             * @description 上下文信息
             */
            context?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * IntentResponse
         * @description 意图识别响应
         */
        IntentResponse: {
            /**
             * Intent
             * @description 识别的意图类型
             */
            intent: string;
            /**
             * Confidence
             * @description 置信度
             * @default 1
             */
            confidence: number;
            /**
             * Entities
             * @description 提取的实体
             */
            entities?: {
                [key: string]: unknown;
            };
            /**
             * Query
             * @description 搜索/操作关键词
             */
            query?: string | null;
            /**
             * Response Hint
             * @description 响应提示
             */
            response_hint?: string | null;
        };
        /**
         * KnowledgeGraphResponse
         * @description 知识图谱响应
         */
        KnowledgeGraphResponse: {
            center?: components["schemas"]["ConceptNode"] | null;
            /**
             * Connections
             * @default []
             */
            connections: components["schemas"]["ConceptRelationModel"][];
        };
        /**
         * LLMTestResponse
         * @description LLM 测试响应
         */
        LLMTestResponse: {
            /** Success */
            success: boolean;
            /** Config */
            config: {
                [key: string]: unknown;
            };
            /** Response Content */
            response_content?: string | null;
            /** Error */
            error?: string | null;
            /** Response Time Ms */
            response_time_ms: number;
        };
        /**
         * LearningPathResponse
         * @description 学习路径响应
         */
        LearningPathResponse: {
            /** Concept */
            concept: string;
            /**
             * Prerequisites
             * @default []
             */
            prerequisites: components["schemas"]["ConceptNode"][];
            /**
             * Current Level
             * @default unknown
             */
            current_level: string;
            /**
             * Next Steps
             * @default []
             */
            next_steps: components["schemas"]["ConceptNode"][];
            /**
             * Related Projects
             * @default []
             */
            related_projects: string[];
            /**
             * Related Notes
             * @default []
             */
            related_notes: string[];
        };
        /**
         * MessageInfo
         * @description 消息信息
         */
        MessageInfo: {
            /** Id */
            id: string;
            /** Role */
            role: string;
            /** Content */
            content: string;
            /** Timestamp */
            timestamp: string;
        };
        /**
         * MonthlyReport
         * @description 月报响应
         */
        MonthlyReport: {
            /** Month */
            month: string;
            task_stats: components["schemas"]["TaskStats"];
            note_stats: components["schemas"]["NoteStats"];
            /** Weekly Breakdown */
            weekly_breakdown?: {
                [key: string]: unknown;
            }[];
            /** Ai Summary */
            ai_summary?: string | null;
        };
        /**
         * NoteStats
         * @description 笔记统计
         */
        NoteStats: {
            /**
             * Total
             * @description 笔记总数
             */
            total: number;
            /**
             * Recent Titles
             * @description 最近笔记标题
             */
            recent_titles?: string[];
        };
        /**
         * ParseRequest
         * @description 解析请求
         */
        ParseRequest: {
            /**
             * Text
             * @description 自然语言文本
             */
            text: string;
            /**
             * Session Id
             * @description 会话 ID（对应 LangGraph thread_id）
             * @default default
             */
            session_id: string;
        };
        /**
         * ProjectProgressResponse
         * @description 项目进度响应
         */
        ProjectProgressResponse: {
            /** Project Id */
            project_id: string;
            /** Total Tasks */
            total_tasks: number;
            /** Completed Tasks */
            completed_tasks: number;
            /** Progress Percentage */
            progress_percentage: number;
            /** Status Distribution */
            status_distribution: {
                [key: string]: unknown;
            };
        };
        /**
         * RelatedConceptsResponse
         * @description 相关概念响应
         */
        RelatedConceptsResponse: {
            /** Concept */
            concept: string;
            /** Related */
            related: components["schemas"]["ConceptNode"][];
        };
        /**
         * SearchRequest
         * @description 搜索请求
         */
        SearchRequest: {
            /**
             * Query
             * @description 搜索查询
             */
            query: string;
            /**
             * Limit
             * @description 返回数量
             * @default 5
             */
            limit: number;
        };
        /**
         * SearchResponse
         * @description 搜索响应
         */
        SearchResponse: {
            /** Results */
            results: components["schemas"]["app__routers__search__SearchResult"][];
        };
        /**
         * SessionInfo
         * @description 会话信息
         */
        SessionInfo: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
        };
        /**
         * SessionResponse
         * @description 会话操作响应
         */
        SessionResponse: {
            /** Status */
            status: string;
            /**
             * Message
             * @default
             */
            message: string;
        };
        /**
         * SessionUpdate
         * @description 会话更新请求
         */
        SessionUpdate: {
            /**
             * Title
             * @description 会话标题
             */
            title: string;
        };
        /**
         * SuccessResponse
         * @description 成功响应
         */
        SuccessResponse: {
            /** Success */
            success: boolean;
            /**
             * Message
             * @default
             */
            message: string;
        };
        /**
         * TaskStats
         * @description 任务统计
         */
        TaskStats: {
            /**
             * Total
             * @description 总任务数
             */
            total: number;
            /**
             * Completed
             * @description 已完成数
             */
            completed: number;
            /**
             * Doing
             * @description 进行中数
             */
            doing: number;
            /**
             * Wait Start
             * @description 待开始数
             */
            wait_start: number;
            /**
             * Completion Rate
             * @description 完成率
             */
            completion_rate: number;
        };
        /**
         * Token
         * @description Token 响应模型
         */
        Token: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /**
             * Expires In
             * @default 604800
             */
            expires_in: number;
            user: components["schemas"]["UserResponse"];
        };
        /**
         * TrendPeriod
         * @description 趋势统计周期
         */
        TrendPeriod: {
            /**
             * Date
             * @description 日期（YYYY-MM-DD 或 YYYY-WXX）
             */
            date: string;
            /**
             * Total
             * @description 总任务数
             * @default 0
             */
            total: number;
            /**
             * Completed
             * @description 已完成数
             * @default 0
             */
            completed: number;
            /**
             * Completion Rate
             * @description 完成率（百分比）
             * @default 0
             */
            completion_rate: number;
            /**
             * Notes Count
             * @description 笔记数
             * @default 0
             */
            notes_count: number;
        };
        /**
         * TrendResponse
         * @description 趋势数据响应
         */
        TrendResponse: {
            /**
             * Periods
             * @description 统计周期数组
             */
            periods?: components["schemas"]["TrendPeriod"][];
        };
        /**
         * UserCreate
         * @description 注册请求模型
         */
        UserCreate: {
            /** Username */
            username: string;
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * UserLogin
         * @description 登录请求模型
         */
        UserLogin: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /**
         * UserResponse
         * @description 用户响应模型 - 不含 hashed_password
         */
        UserResponse: {
            /** Id */
            id: string;
            /** Username */
            username: string;
            /** Email */
            email: string;
            /** Is Active */
            is_active: boolean;
            /**
             * Onboarding Completed
             * @default false
             */
            onboarding_completed: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * UserUpdate
         * @description 用户信息更新请求模型
         */
        UserUpdate: {
            /** Onboarding Completed */
            onboarding_completed?: boolean | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WeeklyReport
         * @description 周报响应
         */
        WeeklyReport: {
            /** Start Date */
            start_date: string;
            /** End Date */
            end_date: string;
            task_stats: components["schemas"]["TaskStats"];
            note_stats: components["schemas"]["NoteStats"];
            /** Daily Breakdown */
            daily_breakdown?: {
                [key: string]: unknown;
            }[];
            /** Ai Summary */
            ai_summary?: string | null;
        };
        /**
         * SearchResult
         * @description 搜索结果
         */
        app__api__schemas__entry__SearchResult: {
            /** Entries */
            entries: components["schemas"]["EntryResponse"][];
            /** Query */
            query: string;
        };
        /**
         * SearchResult
         * @description 搜索结果项
         */
        app__routers__search__SearchResult: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Score */
            score: number;
            /** Type */
            type: string;
            /** Tags */
            tags: string[];
            /** File Path */
            file_path: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_entries_entries_get: {
        parameters: {
            query?: {
                /** @description 条目类型: project/task/note/inbox */
                type?: string | null;
                /** @description 状态: waitStart/doing/complete/paused/cancelled */
                status?: string | null;
                /** @description 标签筛选（逗号分隔） */
                tags?: string | null;
                /** @description 父条目ID（用于获取子任务） */
                parent_id?: string | null;
                /** @description 开始日期 (YYYY-MM-DD) */
                start_date?: string | null;
                /** @description 结束日期 (YYYY-MM-DD) */
                end_date?: string | null;
                /** @description 返回数量限制 */
                limit?: number;
                /** @description 偏移量 */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntryListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_entry_entries_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EntryCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_entries_entries_export_get: {
        parameters: {
            query?: {
                /** @description 导出格式: markdown 或 json */
                format?: string;
                /** @description 条目类型: project/task/note/inbox */
                type?: string | null;
                /** @description 开始日期 (YYYY-MM-DD) */
                start_date?: string | null;
                /** @description 结束日期 (YYYY-MM-DD) */
                end_date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_entry_entries__entry_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_entry_entries__entry_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EntryUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_entry_entries__entry_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_entries_entries_search_query_get: {
        parameters: {
            query: {
                /** @description 搜索关键词 */
                q: string;
                /** @description 返回数量限制 */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["app__api__schemas__entry__SearchResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_progress_entries__entry_id__progress_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectProgressResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_vectors_entries_admin_sync_vectors_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
        };
    };
    search_entries_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_knowledge_graph_knowledge_graph__concept__get: {
        parameters: {
            query?: {
                /** @description 关系深度 */
                depth?: number;
            };
            header?: never;
            path: {
                concept: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeGraphResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_related_concepts_related_concepts__concept__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                concept: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelatedConceptsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_learning_path_learning_path__concept__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                concept: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LearningPathResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_daily_report_review_daily_get: {
        parameters: {
            query?: {
                /** @description 日期 (YYYY-MM-DD)，默认今天 */
                date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_weekly_report_review_weekly_get: {
        parameters: {
            query?: {
                /** @description 开始日期 (YYYY-MM-DD)，默认本周一 */
                start_date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeeklyReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_monthly_report_review_monthly_get: {
        parameters: {
            query?: {
                /** @description 月份 (YYYY-MM)，默认本月 */
                month?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonthlyReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trend_data_review_trend_get: {
        parameters: {
            query?: {
                /** @description 统计周期: daily 或 weekly */
                period?: string;
                /** @description daily 模式天数 */
                days?: number;
                /** @description weekly 模式周数 */
                weeks?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrendResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    detect_intent_intent_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IntentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    parse_parse_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_session_session__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_sessions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionInfo"][];
                };
            };
        };
    };
    get_session_messages_sessions__session_id__messages_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageInfo"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_session_sessions__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_session_sessions__session_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_llm_playground_llm_test_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LLMTestResponse"];
                };
            };
        };
    };
    list_feedbacks_feedback_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackListResponse"];
                };
            };
        };
    };
    submit_feedback_feedback_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_feedback_feedback__feedback_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feedback_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserLogin"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    update_me_auth_me_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    claim_default_data_auth_claim_default_data_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DefaultDataClaimResult"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
